version: "3.9"
services:
  n8n-redis:
    image: redis
    ports:
      - "6432:6379"
  n8n-postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: p@ssw0rd
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
  n8n-master:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_DATABASE: postgres
      DB_POSTGRESDB_HOST: n8n-postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_USER: postgres
      DB_POSTGRESDB_PASSWORD: p@ssw0rd
      EXECUTIONS_MODE: queue
      QUEUE_BULL_REDIS_HOST: n8n-redis
    depends_on:
      - n8n-postgres
      - n8n-redis
    volumes:
      - .data/n8n_data:/home/node/.n8n
  n8n-worker:
    image: n8nio/n8n
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_DATABASE: postgres
      DB_POSTGRESDB_HOST: n8n-postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_USER: postgres
      DB_POSTGRESDB_PASSWORD: p@ssw0rd
      EXECUTIONS_MODE: queue
      QUEUE_BULL_REDIS_HOST: n8n-redis
    command: n8n worker
    depends_on:
      - n8n-postgres
      - n8n-redis